import { Poppins } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const popins = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata = {
  title: "Webdigit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className={`whole-body-content webdigit ${popins.className} font-semibold`}
        >
          <header className="NavbarAndHero">
            <Header />
          </header>
        </div>
        <main>{children}</main>
        <div className="Footer">
          <Footer />
        </div>
      </body>
    </html>
  );
}
