import { Poppins } from "next/font/google";
import Header from "./components/Header";
import Hero from "./components/Hero";
import LogoClouds from "./components/LogoClouds";
import { StickyScrollRevealDemo } from "./components/StickyScroll/sticky-scroll-reveal-demo";
import Portfolio from "./components/Portoflio";
import Pricing from "./components/Pricing";
import Stats from "./components/Stats";
import Support from "./components/Support";
import Footer from "./components/Footer";
import "./globals.css";

const popins = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata = {
  title: "Webdigit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className={`whole-body-content webdigit ${popins.className} font-semibold`}
        >
          <header className="NavbarAndHero">
            <Header />
            <Hero />
          </header>
          <div className="LogoClouds">
            <LogoClouds />
          </div>
          <div className="StickyScroll">
            <StickyScrollRevealDemo />
          </div>
          <div className="Portfolio">
            <Portfolio />
          </div>
          <div className="Pricing">
            <Pricing />
          </div>
          <div className="Stats">
            <Stats />
          </div>
          <div className="Support">
            <Support />
          </div>
          <div className="Footer">
            <Footer />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
