name: Deploy Node.js App
on:
  push:
    branches:
      - master # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Or your desired runner OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Specify your required Node.js version
          
      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build app (if needed)
        run: npm run build # Or your build command
        
      - name: Deploy to server
        uses: appleboy/ssh-action@v1 #Example of an SSH action.
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/webdigit-it-solutions
            git pull origin master
            npm install
            npm run build
            pm2 restart webdigit-it-solutions
